---
- name: Copy folder to target 
  synchronize:
          src: ../{{ app }}
          dest: /tmp/ansible-docker

- name: Copy Dockerfile
  template: src=Dockerfile dest=/tmp/ansible-docker/{{ app }}/Dockerfile

- name: Build Docker image from Dockerfile
  docker_image:
          name: "{{ app }}:latest"
          build:
                  path: /tmp/ansible-docker/{{ app }}
                  pull: true
          source: build
          state: present
          force_source: true

- name: Running the container
  docker_container:
          name: "{{ app }}"
          state: started
          image: "{{ app }}:latest"
          ports:
                  - "{{ app_port }}:80"

